"""Generate sample commercial lease contract PDF for testing AI import."""
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor, black, grey
import datetime

c = canvas.Canvas("/app/uploads/sample_contract.pdf", pagesize=A4)
w, h = A4

primary = HexColor("#1a365d")
accent = HexColor("#2b6cb0")
light_bg = HexColor("#f7fafc")
border = HexColor("#cbd5e0")

# === Header ===
c.setFillColor(primary)
c.rect(0, h-45*mm, w, 45*mm, fill=1, stroke=0)

c.setFillColor(HexColor("#ffffff"))
c.setFont("Helvetica-Bold", 22)
c.drawString(25*mm, h-28*mm, "COMMERCIAL LEASE AGREEMENT")

c.setFont("Helvetica", 10)
c.drawRightString(w-25*mm, h-28*mm, "CAMP-SUNSHINE-2026-001")

c.setFont("Helvetica", 9)
c.setFillColor(HexColor("#a0aec0"))
c.drawString(25*mm, h-38*mm, "Sunshine Plaza Shopping Mall | Commercial Property Lease Contract")

# === Title Section ===
y = h - 60*mm
c.setFillColor(black)
c.setFont("Helvetica-Bold", 14)
c.drawString(25*mm, y, "LEASE CONTRACT DETAILS")

y -= 8*mm
c.setStrokeColor(border)
c.setLineWidth(0.5)
c.line(25*mm, y+2*mm, w-25*mm, y+2*mm)

# === Info Table ===
fields = [
    ("Contract Number", "CAMP-L1-2026-0042"),
    ("Tenant Name", "Starbucks Coffee (China) Co., Ltd."),
    ("Tenant ID", "TEN-0017"),
    ("Unit Code", "L1-03"),
    ("Unit Location", "Sunshine Plaza, Level 1, Unit L1-03 (Near Atrium East)"),
    ("Leasable Area", "280 m2 (Gross: 320 m2)"),
    ("Business Type", "F&B / Cafe / Beverage"),
    ("Monthly Rent", "RMB 85,000.00"),
    ("Management Fee", "RMB 12,600 / month"),
    ("Deposit (3 months)", "RMB 255,000.00"),
    ("Lease Start Date", "2026-05-01"),
    ("Lease End Date", "2031-04-30"),
    ("Lease Term", "5 Years (60 months)"),
    ("Rent Free Period", "45 days (May 1 - June 14, 2026)"),
    ("Annual Rent Increase", "5% per annum after Year 2"),
    ("Payment Frequency", "Quarterly (Payable in advance)"),
    ("Payment Due Date", "Within 10 days before each quarter start"),
    ("Currency", "CNY (Chinese Yuan Renminbi)"),
]

row_h = 6.5 * mm
for i, (label, value) in enumerate(fields):
    cy = y - i * row_h
    if i % 2 == 0:
        c.setFillColor(light_bg)
        c.rect(25*mm, cy - row_h + 1.5*mm, w-50*mm, row_h, fill=1, stroke=0)

    c.setFillColor(HexColor("#4a5568"))
    c.setFont("Helvetica-Bold", 9)
    c.drawString(27*mm, cy - 3*mm, label + ":")

    c.setFillColor(black)
    c.setFont("Helvetica", 9)
    c.drawString(85*mm, cy - 3*mm, value)

# === Terms Section ===
terms_y = cy - 15*mm

c.setFillColor(primary)
c.setFont("Helvetica-Bold", 12)
c.drawString(25*mm, terms_y, "KEY TERMS & CONDITIONS")

terms_y -= 7*mm
c.setStrokeColor(border)
c.line(25*mm, terms_y+2*mm, w-25*mm, terms_y+2*mm)

terms_text = [
    "1. The Tenant shall use the Premises solely for the operation of a Starbucks coffee shop.",
    "2. Operating hours shall be consistent with Sunshine Plaza mall hours (10:00 - 22:00).",
    "3. Tenant is responsible for interior fit-out costs and utility connections.",
    "4. Landlord provides base building HVAC, fire safety, and common area maintenance.",
    "5. Sub-leasing is permitted only with prior written consent from the Landlord.",
    "6. Early termination requires 6 months written notice and 3 months rent penalty.",
    "7. Insurance: Tenant must maintain public liability insurance of min RMB 5,000,000.",
    "8. Renewal option: Tenant has right to renew for additional 5 years at market rate.",
]

c.setFont("Helvetica", 8.5)
for line in terms_text:
    terms_y -= 5*mm
    c.setFillColor(HexColor("#2d3748"))
    c.drawString(27*mm, terms_y, line)

# === Signature Section ===
sig_y = terms_y - 15*mm
c.setStrokeColor(border)
c.line(25*mm, sig_y+5*mm, w-25*mm, sig_y+5*mm)

c.setFont("Helvetica-Bold", 10)
c.setFillColor(primary)
c.drawString(25*mm, sig_y, "SIGNATORIES")

sig_y -= 12*mm

c.setFillColor(black)
c.setFont("Helvetica-Bold", 9)
c.drawString(25*mm, sig_y, "LANDLORD:")
c.setFont("Helvetica", 9)
c.drawString(25*mm, sig_y - 4*mm, "Sunshine Plaza Management Co., Ltd.")
c.drawString(25*mm, sig_y - 8*mm, "Authorized Signatory: _______________________")
c.drawString(25*mm, sig_y - 12*mm, "Date: _______________")

c.setFont("Helvetica-Bold", 9)
c.drawString(100*mm, sig_y, "TENANT:")
c.setFont("Helvetica", 9)
c.drawString(100*mm, sig_y - 4*mm, "Starbucks Coffee (China) Co., Ltd.")
c.drawString(100*mm, sig_y - 8*mm, "Authorized Signatory: _______________________")
c.drawString(100*mm, sig_y - 12*mm, "Date: _______________")

# === Footer ===
footer_y = 20*mm
c.setFillColor(grey)
c.setFont("Helvetica", 7)
c.drawString(25*mm, footer_y, "Document generated by CAMP System | Sample contract for testing purposes only.")
c.drawRightString(w-25*mm, footer_y, "Page 1 of 1 | Generated: " + datetime.date.today().isoformat())

# Border frame
c.setStrokeColor(border)
c.setLineWidth(1)
c.roundRect(10*mm, 10*mm, w-20*mm, h-20*mm, 3*mm, fill=0, stroke=1)

c.save()
print("PDF generated successfully: /app/uploads/sample_contract.pdf")
