"""add leasing fields to unit

Revision ID: 9fcf0bf255f4
Revises: 
Create Date: 2026-04-18 18:03:11.241279
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fcf0bf255f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('brand_tier', sa.Enum('S', 'A', 'B', 'C', 'LIANFA', 'UNKNOWN', name='brandtier'), nullable=True, comment='Brand tier: S/A/B/C/lianfa'))
    op.add_column('tenants', sa.Column('is_flagship', sa.Boolean(), nullable=True, comment='Is flagship store'))
    op.add_column('tenants', sa.Column('is_first_entry', sa.Boolean(), nullable=True, comment='Is first entry brand'))
    op.add_column('units', sa.Column('vacancy_days', sa.Integer(), nullable=True, comment='Vacancy days'))
    op.add_column('units', sa.Column('leasing_type', sa.String(length=20), nullable=True, comment='Leasing type: new/renewal/adjustment'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'leasing_type')
    op.drop_column('units', 'vacancy_days')
    op.drop_column('tenants', 'is_first_entry')
    op.drop_column('tenants', 'is_flagship')
    op.drop_column('tenants', 'brand_tier')
    # ### end Alembic commands ###
